/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2021-10-28 16:29:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\" />\r\n");
      out.write("    <meta name=\"generator\" content=\"Hugo 0.80.0\" />\r\n");
      out.write("    <title>HOME TRAINING</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/4.6/examples/carousel/\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\" integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\" crossorigin=\"anonymous\" />\r\n");
      out.write("\r\n");
      out.write("    <title>Hello, world!</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"../assets/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .bd-placeholder-img {\r\n");
      out.write("        font-size: 1.125rem;\r\n");
      out.write("        text-anchor: middle;\r\n");
      out.write("        -webkit-user-select: none;\r\n");
      out.write("        -moz-user-select: none;\r\n");
      out.write("        -ms-user-select: none;\r\n");
      out.write("        user-select: none;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      @media (min-width: 768px) {\r\n");
      out.write("        .bd-placeholder-img-lg {\r\n");
      out.write("          font-size: 3.5rem;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <!-- <link href=\"style.css\" rel=\"stylesheet\" /> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav class=\"navbar navbar-expand-md navbar-dark fixed-top bg-dark\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">HOME TRAINING</a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarCollapse\" aria-controls=\"navbarCollapse\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("          <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("            <li class=\"nav-item active\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">INICIO<span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link\" href=\"#\">RUTINAS</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link disabled\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">CONTACTO</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form class=\"form-inline mt-2 mt-md-0\">\r\n");
      out.write("            <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\" aria-label=\"Search\" />\r\n");
      out.write("            <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <main role=\"main\">\r\n");
      out.write("      <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("        <ol class=\"carousel-indicators\">\r\n");
      out.write("          <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("          <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("          <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("          <div class=\"carousel-item active\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\" :  \" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title></title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\"></text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"carousel-caption text-left\">\r\n");
      out.write("                <h1>HOME TRAINING</h1>\r\n");
      out.write("                <p>ENTRENAMIENTOS EN CASA.</p>\r\n");
      out.write("                <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Sign up today</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\" :  \" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title></title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\"></text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"carousel-caption\">\r\n");
      out.write("                <h1>HOME TRAINING</h1>\r\n");
      out.write("                <p>ENTRENA DESDE CASA COMO SI ESTUVIESES EN EL GIMNASIO</p>\r\n");
      out.write("                <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Learn more</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"carousel-item\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\" :  \" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title></title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\"></text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("              <div class=\"carousel-caption text-right\">\r\n");
      out.write("                <h1>HOME TRAINING </h1>\r\n");
      out.write("                <p>EL GIMNASIO EN CASA.</p>\r\n");
      out.write("                <p><a class=\"btn btn-lg btn-primary\" href=\"#\">Browse gallery</a></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Marketing messaging and featurettes\r\n");
      out.write("  ================================================== -->\r\n");
      out.write("      <!-- Wrap the rest of the page in another container to center all the content. -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"container marketing\">\r\n");
      out.write("        <!-- Three columns of text below the carousel -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: 140x140\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">140x140</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <h2>HOME TRAINING</h2>\r\n");
      out.write("            <p>GIMNASION EN CASA</p>\r\n");
      out.write("            <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col-lg-4 -->\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: 140x140\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">140x140</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <h2>Heading</h2>\r\n");
      out.write("            <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>\r\n");
      out.write("            <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col-lg-4 -->\r\n");
      out.write("          <div class=\"col-lg-4\">\r\n");
      out.write("            <svg class=\"bd-placeholder-img rounded-circle\" width=\"140\" height=\"140\" xmlns=\"http://www.w3.org/2000/svg\" role=\"img\" aria-label=\"Placeholder: 140x140\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\">\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#777\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#777\" dy=\".3em\">140x140</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("\r\n");
      out.write("            <h2>Heading</h2>\r\n");
      out.write("            <p>And lastly this, the third column of representative placeholder content.</p>\r\n");
      out.write("            <p><a class=\"btn btn-secondary\" href=\"#\">View details &raquo;</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.col-lg-4 -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- /.row -->\r\n");
      out.write("\r\n");
      out.write("        <!-- START THE FEATURETTES -->\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"featurette-divider\" />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row featurette\">\r\n");
      out.write("          <div class=\"col-md-7\">\r\n");
      out.write("            <h2 class=\"featurette-heading\">First featurette heading. <span class=\"text-muted\">It?ll blow your mind.</span></h2>\r\n");
      out.write("            <p class=\"lead\">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5\">\r\n");
      out.write("            <svg\r\n");
      out.write("              class=\"bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto\"\r\n");
      out.write("              width=\"500\"\r\n");
      out.write("              height=\"500\"\r\n");
      out.write("              xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              role=\"img\"\r\n");
      out.write("              aria-label=\"Placeholder: 500x500\"\r\n");
      out.write("              preserveAspectRatio=\"xMidYMid slice\"\r\n");
      out.write("              focusable=\"false\"\r\n");
      out.write("            >\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#eee\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#aaa\" dy=\".3em\">500x500</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"featurette-divider\" />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row featurette\">\r\n");
      out.write("          <div class=\"col-md-7 order-md-2\">\r\n");
      out.write("            <h2 class=\"featurette-heading\">Oh yeah, it?s that good. <span class=\"text-muted\">See for yourself.</span></h2>\r\n");
      out.write("            <p class=\"lead\">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5 order-md-1\">\r\n");
      out.write("            <svg\r\n");
      out.write("              class=\"bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto\"\r\n");
      out.write("              width=\"500\"\r\n");
      out.write("              height=\"500\"\r\n");
      out.write("              xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              role=\"img\"\r\n");
      out.write("              aria-label=\"Placeholder: 500x500\"\r\n");
      out.write("              preserveAspectRatio=\"xMidYMid slice\"\r\n");
      out.write("              focusable=\"false\"\r\n");
      out.write("            >\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#eee\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#aaa\" dy=\".3em\">500x500</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"featurette-divider\" />\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row featurette\">\r\n");
      out.write("          <div class=\"col-md-7\">\r\n");
      out.write("            <h2 class=\"featurette-heading\">And lastly, this one. <span class=\"text-muted\">Checkmate.</span></h2>\r\n");
      out.write("            <p class=\"lead\">\r\n");
      out.write("              And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-md-5\">\r\n");
      out.write("            <svg\r\n");
      out.write("              class=\"bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto\"\r\n");
      out.write("              width=\"500\"\r\n");
      out.write("              height=\"500\"\r\n");
      out.write("              xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("              role=\"img\"\r\n");
      out.write("              aria-label=\"Placeholder: 500x500\"\r\n");
      out.write("              preserveAspectRatio=\"xMidYMid slice\"\r\n");
      out.write("              focusable=\"false\"\r\n");
      out.write("            >\r\n");
      out.write("              <title>Placeholder</title>\r\n");
      out.write("              <rect width=\"100%\" height=\"100%\" fill=\"#eee\" />\r\n");
      out.write("              <text x=\"50%\" y=\"50%\" fill=\"#aaa\" dy=\".3em\">500x500</text>\r\n");
      out.write("            </svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"featurette-divider\" />\r\n");
      out.write("\r\n");
      out.write("        <!-- /END THE FEATURETTES -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("      <!-- FOOTER -->\r\n");
      out.write("      <footer class=\"container\">\r\n");
      out.write("        <p class=\"float-right\"><a href=\"#\">Back to top</a></p>\r\n");
      out.write("        <p>&copy; 2017-2021 Company, Inc. &middot; <a href=\"#\">Privacy</a> &middot; <a href=\"#\">Terms</a></p>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      window.jQuery || document.write('<script src=\"../assets/js/vendor/jquery.slim.min.js\"><\\/script>')\r\n");
      out.write("    </script>\r\n");
      out.write("    <script src=\"../assets/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Optional JavaScript; choose one of the two! -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Option 2: Separate Popper and Bootstrap JS -->\r\n");
      out.write("    <!--\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js\" integrity=\"sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    -->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
